// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package neoroute

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *reqStructTesting) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SomeField":
			z.SomeField, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "SomeField")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z reqStructTesting) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "SomeField"
	err = en.Append(0x81, 0xa9, 0x53, 0x6f, 0x6d, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt(z.SomeField)
	if err != nil {
		err = msgp.WrapError(err, "SomeField")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z reqStructTesting) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "SomeField"
	o = append(o, 0x81, 0xa9, 0x53, 0x6f, 0x6d, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64)
	o = msgp.AppendInt(o, z.SomeField)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *reqStructTesting) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SomeField":
			z.SomeField, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SomeField")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z reqStructTesting) Msgsize() (s int) {
	s = 1 + 10 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *respStructTesting) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SomeField":
			z.SomeField, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SomeField")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z respStructTesting) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "SomeField"
	err = en.Append(0x81, 0xa9, 0x53, 0x6f, 0x6d, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.SomeField)
	if err != nil {
		err = msgp.WrapError(err, "SomeField")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z respStructTesting) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "SomeField"
	o = append(o, 0x81, 0xa9, 0x53, 0x6f, 0x6d, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64)
	o = msgp.AppendString(o, z.SomeField)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *respStructTesting) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SomeField":
			z.SomeField, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SomeField")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z respStructTesting) Msgsize() (s int) {
	s = 1 + 10 + msgp.StringPrefixSize + len(z.SomeField)
	return
}
