// Code generated by neogen. DO NOT EDIT.
package definitions

type EchoRequest struct {
	Message string `msg:"message"`
}

type EchoResponse struct {
	Message       string `msg:"message"`
	RequestNumber int64  `msg:"requestNumber"`
}

type NewPunEvent struct {
	Pun string `msg:"pun"`
}

type SubmitPunRequest struct {
	Pun string `msg:"pun"`
}
