package main

import (
	"flag"
	"os"
	"strings"

	"github.com/Liphium/neoroute/cmd/neogen/languages"
)

var (
	path    = flag.String("path", "", "package for actual")
	target  = flag.String("target", string(languages.LanguageGo), "target language for generation")
	verbose = flag.Bool("v", false, "verbose diagnostics")
)

func main() {
	currentFile := os.Getenv("GOFILE")
	if currentFile == "" {
		currentFile = "main.go"
	}

	newFileName := strings.TrimSuffix(currentFile, ".go") + "_gen.go"

	file, err := os.Create(newFileName)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	code := `// Code generated by neogen. DO NOT EDIT.
package ` + os.Getenv("GOPACKAGE") + `

import "fmt"

func SayHello() {
	fmt.Println("Hello World")
}
`
	_, err = file.WriteString(code)
	if err != nil {
		panic(err)
	}
}
