package languages

import (
	"fmt"
	"maps"
	"os"
	"slices"
	"strings"

	"github.com/Liphium/neoroute/cmd/neogen/engine"
	"github.com/Liphium/neoroute/cmd/neogen/util"
	"github.com/Liphium/neoroute/neoschema"
)

var goTypeMap = map[neoschema.SchemaType]string{
	neoschema.TypeBool:         "bool",
	neoschema.TypeByte:         "byte",
	neoschema.TypeInt32:        "int32",
	neoschema.TypeInt64:        "int64",
	neoschema.TypeFloat32:      "float32",
	neoschema.TypeFloat64:      "float64",
	neoschema.TypeString:       "string",
	neoschema.TypeSerializable: "neoschema.UsableMessage",
}

func GetType(packed neoschema.PackedType) (string, error) {
	switch schema := packed.(type) {
	case *neoschema.StructType:
		return util.ToCamelCase(schema.Name, true), nil
	case *neoschema.ReferenceType:
		return util.ToCamelCase(schema.Object, true), nil
	case *neoschema.ArrayType:
		elem, err := GetType(schema.Element)
		if err != nil {
			return "", err
		}
		return "[]" + elem, nil
	case *neoschema.MapType:
		k, err := GetType(schema.Key)
		if err != nil {
			return "", err
		}
		v, err := GetType(schema.Value)
		if err != nil {
			return "", err
		}
		return "map[" + k + "]" + v, nil
	case *neoschema.NullableType:
		elem, err := GetType(schema.Element)
		if err != nil {
			return "", err
		}
		return "*" + elem, nil
	default:
		t, ok := goTypeMap[schema.Type()]
		if !ok {
			return "", fmt.Errorf("unknown type: %s", schema.Type())
		}
		return t, nil
	}
}

const GoObjectsTemplate = `// Code generated by neogen. DO NOT EDIT.
package {{ .Object.PackageName }}

{{- if .Object.HasSchema }}
import "github.com/Liphium/neoroute/neoschema"
{{- end }}

{{ range $name, $obj := .Object.Registry }}
{{- $struct := toStruct $obj -}}
{{- if $struct }}
type {{ camel $name true }} struct {
{{- range $fName, $fType := $struct.Fields }}
	{{ camel $fName true }} {{ getType $fType }} ` + "`msg:\"{{ $fName }}\"`" + `
{{- end }}
}
{{- end }}
{{ end }}`

const GoTransporterTemplate = `// Code generated by neogen. DO NOT EDIT.
package {{ .Object.PackageName }}

import (
	{{- if eq .Object.Type "http" }}
	"net/url"
	{{- end }}
	"github.com/Liphium/neoroute/client"
	"github.com/Liphium/neoroute/client/transporter/{{ .Object.Type }}"
)

type {{ .Object.Name }} struct {
	*{{ .Object.Type }}.{{ .Object.TypeName }}Transporter
	receiver *client.Receiver
}

{{ if eq .Object.Type "http" -}}
func New{{ .Object.Name }}(config client.Config, method string, u *url.URL) *{{ .Object.Name }} {
	r := client.NewReceiver(config)
	return &{{ .Object.Name }}{
		HTTPTransporter: http.NewHTTPTransporter(r, method, u),
		receiver: r,
	}
}
{{- else -}}
func New{{ .Object.Name }}(config client.Config) *{{ .Object.Name }} {
	r := client.NewReceiver(config)
	return &{{ .Object.Name }}{
		WebSocketTransporter: websocket.NewWebSocketTransporter(r),
		receiver: r,
	}
}
{{- end }}

{{ range $name, $event := .Object.Events }}
func (c *{{ $.Object.Name }}) Receive{{ camel $name true }}(handler func(event {{ getType $event }})) {
	client.Receive[{{ getType $event }}, *{{ getType $event }}](c.receiver, "{{ $name }}", func(c *client.Ctx, event {{ getType $event }}) {
		handler(event)
	})
}
{{- end }}

{{ range $name, $route := .Object.Routes }}
func (c *{{ $.Object.Name }}) Send{{ camel $name true }}({{- if $route.HasRequest }}payload {{ getType $route.Request }}{{ end -}}) ({{- if $route.HasResponse }}{{ getType $route.Response }}, {{ end -}}error) {
	{{- $sendType := $route.GetSendType -}}
	{{- if eq $sendType $.Object.Const.SendRequestResponse }}
	return client.Send[{{ getType $route.Response }}](c.receiver, "{{ $name }}", payload)
	{{- else if eq $sendType $.Object.Const.SendOK }}
	return client.SendOk(c.receiver, "{{ $name }}", payload)
	{{- else if eq $sendType $.Object.Const.SendOKNoRequest }}
	return client.SendOkNoRequest(c.receiver, "{{ $name }}")
	{{- else if eq $sendType $.Object.Const.SendNoRequest }}
	return client.SendNoRequest[{{ getType $route.Response }}](c.receiver, "{{ $name }}")
	{{- else if eq $sendType $.Object.Const.SendNoResponse }}
	return client.SendNoResponse(c.receiver, "{{ $name }}", payload)
	{{- else if eq $sendType $.Object.Const.SendPing }}
	return client.SendPing(c.receiver, "{{ $name }}")
	{{- end }}
}
{{ end }}`

const modelFileName = "models.go"

func NewGoConfig() (string, engine.LanguageConfig) {
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		pkg = "generated"
	}

	return modelFileName, engine.LanguageConfig{
		Name:    "go",
		GetType: GetType,
		GetFileMap: func(schema neoschema.Schema) (map[string]engine.TemplateData, error) {
			files := make(map[string]engine.TemplateData)

			// Objects file
			registry := schema.GetCombinedObjectRegistry()
			files[modelFileName] = engine.TemplateData{
				Template: GoObjectsTemplate,
				Object: map[string]any{
					"PackageName": pkg,
					"Registry":    registry,
					"HasSchema": slices.IndexFunc(slices.Collect(maps.Values(registry)), func(t neoschema.PackedType) bool {
						st, ok := t.(*neoschema.StructType)
						if ok {
							for _, field := range st.Fields {
								if mapped, ok := goTypeMap[field.Type()]; ok && strings.Contains(mapped, "neoschema") {
									return true
								}
							}
						}
						return false
					}) != -1,
				},
			}

			// Transporter files
			for name, transport := range schema.Transporters {
				typeName := "HTTP"
				if transport.Type == neoschema.TransporterWebSocket {
					typeName = "WebSocket"
				}

				tData := struct {
					PackageName string
					Name        string
					Type        string
					TypeName    string
					Routes      map[string]neoschema.RouteSchema
					Events      map[string]neoschema.PackedType
					Const       map[string]neoschema.SendType
				}{
					PackageName: pkg,
					Name:        util.ToCamelCase(name+"Connector", true),
					Type:        strings.ToLower(string(typeName)),
					TypeName:    typeName,
					Routes:      transport.Routes,
					Events:      transport.Events,
					Const:       neoschema.SendTypeMap(),
				}

				files["connector_"+strings.ToLower(name)+".go"] = engine.TemplateData{
					Template: GoTransporterTemplate,
					Object:   tData,
				}
			}

			return files, nil
		},
	}
}
