package languages

import (
	"fmt"
	"strings"

	"github.com/Liphium/neoroute/cmd/neogen/engine"
	"github.com/Liphium/neoroute/cmd/neogen/util"
	"github.com/Liphium/neoroute/neoschema"
)

var tsTypeMap = map[neoschema.SchemaType]string{
	neoschema.TypeBool:         "boolean",
	neoschema.TypeByte:         "number",
	neoschema.TypeInt32:        "number",
	neoschema.TypeInt64:        "bigint",
	neoschema.TypeFloat32:      "number",
	neoschema.TypeFloat64:      "number",
	neoschema.TypeString:       "string",
	neoschema.TypeSerializable: "any",
}

func GetTSType(packed neoschema.PackedType) (string, error) {
	switch schema := packed.(type) {
	case *neoschema.StructType:
		return util.ToCamelCase(schema.Name, true), nil
	case *neoschema.ReferenceType:
		return util.ToCamelCase(schema.Object, true), nil
	case *neoschema.ArrayType:
		// Byte array → Uint8Array for proper typed array in TS/JS
		if schema.Element.Type() == neoschema.TypeByte {
			return "Uint8Array", nil
		}
		elem, err := GetTSType(schema.Element)
		if err != nil {
			return "", err
		}
		return elem + "[]", nil
	case *neoschema.MapType:
		k, err := GetTSType(schema.Key)
		if err != nil {
			return "", err
		}
		v, err := GetTSType(schema.Value)
		if err != nil {
			return "", err
		}
		return "Record<" + k + ", " + v + ">", nil
	case *neoschema.NullableType:
		elem, err := GetTSType(schema.Element)
		if err != nil {
			return "", err
		}
		return elem + " | null", nil
	default:
		t, ok := tsTypeMap[schema.Type()]
		if !ok {
			return "", fmt.Errorf("unknown type: %s", schema.Type())
		}
		return t, nil
	}
}

const TSObjectsTemplate = `// Code generated by neogen. DO NOT EDIT.

{{ range $name, $obj := .Object.Registry }}
{{- $struct := toStruct $obj -}}
{{- if $struct }}
export interface {{ camel $name true }} {
{{- range $field := $struct.Fields }}
	{{ $field.Name }}: {{ getType $field.Type }};
{{- end }}
}
{{- end }}
{{ end }}`

const TSTransporterTemplate = `// Code generated by neogen. DO NOT EDIT.
import {
    Client,
    type Config,
    {{- if eq .Object.Type "http" }}
    applyHTTP,
    {{- else if eq .Object.Type "websocket" }}
    WebSocketTransporter,
    type WebSocketOptions,
	{{- end }}
    UserError,
    Ctx
} from '@liphium/neoroute-ts';
{{ if .Object.HasObjects }}
import {
{{- range $name, $obj := .Object.Registry }}
    type {{ camel $name true }},
{{- end }}
} from './models.js';
{{ end }}

export class {{ .Object.Name }} {{ if eq .Object.Type "http" }}{{ else }}extends {{ .Object.TypeName }}Transporter{{ end }} {
	private cl: Client;

	constructor(config: Config{{ if eq .Object.Type "http" }}, method: string, url: string{{ else if eq .Object.Type "websocket" }} & WebSocketOptions{{ end }}) {
		const client = new Client(config);
		{{- if eq .Object.Type "http" }}
		applyHTTP(client, method, url);
		{{- else }}
		super(client, config);
		{{- end }}
		this.cl = client;
	}

{{ range $name, $event := .Object.Events }}
	public on{{ camel $name true }}(handler: (event: {{ getType $event }}) => void): void {
		this.cl.receive<{{ getType $event }}>("{{ $name }}", (c: Ctx, event: {{ getType $event }}) => {
			handler(event);
		});
	}
{{- end }}

{{ range $name, $route := .Object.Routes }}
	public async {{ camel $name false }}({{- if $route.HasRequest }}payload: {{ getType $route.Request }}{{ end -}}): Promise<{{ if $route.HasResponse }}{{ getType $route.Response }} | {{ end }}UserError{{ if not $route.HasResponse }} | void{{ end }}> {
		{{- $sendType := $route.GetSendType -}}
		{{- if eq $sendType $.Object.Const.SendRequestResponse }}
		return this.cl.send<{{ getType $route.Response }}, {{ getType $route.Request }}>("{{ $name }}", payload);
		{{- else if eq $sendType $.Object.Const.SendOK }}
		return this.cl.sendOk<{{ getType $route.Request }}>("{{ $name }}", payload);
		{{- else if eq $sendType $.Object.Const.SendOKNoRequest }}
		return this.cl.sendOkNoRequest("{{ $name }}");
		{{- else if eq $sendType $.Object.Const.SendNoRequest }}
		return this.cl.sendNoRequest<{{ getType $route.Response }}>("{{ $name }}");
		{{- else if eq $sendType $.Object.Const.SendNoResponse }}
		return this.cl.sendNoResponse<{{ getType $route.Request }}>("{{ $name }}", payload);
		{{- else if eq $sendType $.Object.Const.SendPing }}
		return this.cl.sendPing("{{ $name }}");
		{{- end }}
	}
{{ end }}
}`

const tsModelFileName = "models.ts"

func NewTSConfig() engine.LanguageConfig {
	return engine.LanguageConfig{
		Name:    "typescript",
		GetType: GetTSType,
		GetFileMap: func(schema neoschema.Schema) (map[string]engine.TemplateData, error) {
			files := make(map[string]engine.TemplateData)

			registry := schema.GetCombinedObjectRegistry()
			files[tsModelFileName] = engine.TemplateData{
				Template: TSObjectsTemplate,
				Object: map[string]any{
					"Registry": registry,
				},
			}

			for name, transport := range schema.Transporters {
				typeName := "HTTP"
				if transport.Type == neoschema.TransporterWebSocket {
					typeName = "WebSocket"
				}

				tData := struct {
					Name       string
					Type       string
					TypeName   string
					Routes     map[string]neoschema.RouteSchema
					Events     map[string]neoschema.PackedType
					Const      map[string]neoschema.SendType
					HasObjects bool
					Registry   map[string]neoschema.PackedType
				}{
					Name:       util.ToCamelCase(name+"Connector", true),
					Type:       strings.ToLower(string(typeName)),
					TypeName:   typeName,
					Routes:     transport.Routes,
					Events:     transport.Events,
					Const:      neoschema.SendTypeMap(),
					HasObjects: len(registry) > 0,
					Registry:   registry,
				}

				files["connector_"+strings.ToLower(name)+".ts"] = engine.TemplateData{
					Template: TSTransporterTemplate,
					Object:   tData,
				}
			}

			return files, nil
		},
	}
}
