// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package main

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Request) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "field1":
			z.Field1, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		case "field2":
			z.Field2, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Request) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "field1"
	err = en.Append(0x82, 0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field1)
	if err != nil {
		err = msgp.WrapError(err, "Field1")
		return
	}
	// write "field2"
	err = en.Append(0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Field2)
	if err != nil {
		err = msgp.WrapError(err, "Field2")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Request) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "field1"
	o = append(o, 0x82, 0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Field1)
	// string "field2"
	o = append(o, 0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt64(o, z.Field2)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Request) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "field1":
			z.Field1, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		case "field2":
			z.Field2, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Request) Msgsize() (s int) {
	s = 1 + 7 + msgp.StringPrefixSize + len(z.Field1) + 7 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Response) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "field2":
			z.Field2, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		case "field1":
			z.Field1, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Response) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "field2"
	err = en.Append(0x82, 0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Field2)
	if err != nil {
		err = msgp.WrapError(err, "Field2")
		return
	}
	// write "field1"
	err = en.Append(0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field1)
	if err != nil {
		err = msgp.WrapError(err, "Field1")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Response) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "field2"
	o = append(o, 0x82, 0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt64(o, z.Field2)
	// string "field1"
	o = append(o, 0xa6, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Field1)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Response) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "field2":
			z.Field2, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		case "field1":
			z.Field1, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Response) Msgsize() (s int) {
	s = 1 + 7 + msgp.Int64Size + 7 + msgp.StringPrefixSize + len(z.Field1)
	return
}
