// Code generated by neogen. DO NOT EDIT.
package definitions

type Request struct {
	Field1 string `msg:"field1"`
	Field2 int64  `msg:"field2"`
}

type Response struct {
	Field1 string `msg:"field1"`
	Field2 int64  `msg:"field2"`
}
