name: Trigger Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  trigger-release:
    if: "github.event.head_commit.message == 'chore: release deeznuts12367'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run release pipeline
        run: bash scripts/release-pipe.sh "${{ github.head_ref || github.ref_name }}"
        env:
          GH_TOKEN: ${{ github.token }}
